name: CI

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:


jobs:
  gir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frida-gum
        uses: actions/checkout@v2
      - name: Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install \
            gobject-introspection \
            libdwarf-dev \
            libelf-dev \
            libgirepository1.0-dev \
            libglib2.0-dev \
            libjson-glib-dev \
            libsoup2.4-dev \
            libsqlite3-dev \
            libunwind-dev \
            ninja-build
          pip install meson==0.61.2
      - name: Build
        run: |
          meson setup \
            -Dgumpp=enabled \
            -Dgumjs=enabled \
            build
          meson compile -C build

  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [amd64_x86, amd64]
    steps:
      - name: Checkout frida-gum
        uses: actions/checkout@v2
      - name: Dependencies
        run: pip install meson==0.61.2 ninja
      - name: Environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - name: Build
        run: |
          meson setup `
            --default-library static `
            -Dgumpp=enabled `
            -Dgumjs=enabled `
            build
          meson compile -C build
      - name: Test
        run: |
          Copy-Item build\bindings\gumpp\frida-gumpp-1.0.dll -Destination build\tests\
          .\build\tests\gum-tests.exe

  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frida-gum
        uses: actions/checkout@v2
      - name: Dependencies
        run: pip install meson==0.61.2 ninja
      - name: Build
        run: |
          meson setup \
            --default-library static \
            -Dgumpp=enabled \
            -Dgumjs=enabled \
            build
          meson compile -C build
      - name: Test
        run: ./build/tests/gum-tests
